name: cloud_functions_app_sample
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.4
  cloud_firestore_odm: ^1.0.0-dev.4
  cloud_functions: ^3.2.3
  connectivity_plus: ^2.0.3
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.0.3
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.3
  firebase_storage: ^10.2.3
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.3.0
  flutter_launcher_icons: ^0.9.2
  flutter_linkify: ^5.0.2
  flutter_local_notifications: ^9.1.4
  flutter_localizations:
    sdk: flutter
  flutter_native_image: ^0.0.6+1
  flutter_spinkit: ^5.1.0
  # flutterfire_ui: ^0.2.0+2
  freezed_annotation: ^1.0.0
  gap: ^2.0.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  keyboard_actions: ^3.4.0
  modal_bottom_sheet: ^2.0.0
  package_info_plus: ^1.3.0
  permission_handler: ^8.3.0
  photo_view: ^0.13.0
  provider: ^6.0.1
  shared_preferences: ^2.0.9
  url_launcher: ^6.0.15
  uuid: ^3.0.5
  wechat_assets_picker: ^6.2.4

dev_dependencies:
  build_runner: ^2.1.5
  cloud_firestore_odm_generator: ^1.0.0-dev.4
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.0.0
  json_serializable: ^6.1.1

flutter:
  uses-material-design: true
